on:
  push:
    paths:
      - 'contents/**'

name: CreatePDFs

jobs:
  makepdfs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: mkrakowitzer/actions-makepdfs@master
      if: github.ref == 'refs/heads/master'
      with:
        markdown_dir: contents
        output_dir: pdf
    - uses: actions/upload-artifact@v1
      with:
        name: platform-architecture-docs
        path: tmp